name: Test Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 13 * * *' # run at UTC 1 pm

jobs:
  build-all-targets:
    strategy:
      matrix:
        include:
          - target: 'native'
            optimizaton: 'Debug'
          - target: 'native'
            optimizaton: 'ReleaseSafe'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Check formatting
        run:  |
          zig fmt --check .

      - name: Build Libraries
        run: |
          zig build -Doptimize=${{ matrix.optimizaton }}

      - name: Run Unit Tests
        run: |
          zig build -Doptimize=${{ matrix.optimizaton }} test --summary all

      - name: Run Examples
        run: |
          zig build -Doptimize=${{ matrix.optimizaton }} examples --summary all

      - name: Run Benchmarks
        run: |
          zig build -Doptimize=${{ matrix.optimizaton }} benchmarks --summary all
